'use strict';function z(g,a,b,d){g.u.sc(g.Za,a,b,d,void 0)}function H(g,a,b,d){g.u.ca?z(g,a,b,d):g.u.lf()._OnMessageFromDOM({type:"event",component:g.Za,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(g,a,b){g.u.C(g.Za,a,b)}function L(g,a){for(const [b,d]of a)J(g,b,d)}function M(g){g.Rb||(g.u.We(g.fe),g.Rb=!0)}window.wb=class{constructor(g,a){this.u=g;this.Za=a;this.Rb=!1;this.fe=()=>this.Ca()}hd(){}Ca(){}};function N(g){-1!==g.Pa&&(self.clearTimeout(g.Pa),g.Pa=-1)}
window.Ne=class{constructor(g,a){this.Pc=g;this.Bg=a;this.Pa=-1;this.Sb=-Infinity;this.ge=()=>{this.Pa=-1;this.Sb=Date.now();this.eb=!0;this.Pc();this.eb=!1};this.Od=this.eb=!1}f(){N(this);this.ge=this.Pc=null}};"use strict";function O(g,a){J(g,"get-element",b=>{const d=g.ba.get(b.elementId);return a(d,b)})}
window.Wg=class extends self.wb{constructor(g,a){super(g,a);this.ba=new Map;this.Oc=!0;L(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ba.get(b);this.Oc&&d.parentElement.removeChild(d);this.ba.delete(b)}}],["set-visible",b=>{this.Oc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Oc){var d=this.ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>{{const d=this.ba.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Mg?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.Qg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let f=!1,n=!1;function q(){if(!f){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}f=!0}return n}let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=await w(m);return(new TextDecoder("utf-8")).decode(m)}
function w(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const x=[];let C=0;window.RealFile=window.File;const E=[],A=new Map,F=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Bb=class m{constructor(c){this.ca=c.Sg;this.qa=null;this.F="";this.ec=c.Pg;
this.ub={};this.Ia=this.tb=null;this.Pb=[];this.hb=this.K=this.Na=null;this.Ma=-1;this.Gg=()=>this.Lf();this.La=[];this.v=c.he;this.fb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Vb=this.ia=null;"html5"!==
this.v&&"playable-ad"!==this.v||!this.fb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.vf(k));this.C("runtime",
"create-job-worker",()=>this.wf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.Ad(c)):this.Ad(c)}f(){this.yc();this.qa&&(this.qa=this.qa.onmessage=null);this.tb&&(this.tb.terminate(),this.tb=null);this.Ia&&(this.Ia.f(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Ie(){return g&&"cordova"===this.v}rc(){const c=navigator.userAgent;return g&&e.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Ge(){return a}pd(){return a&&e.has(this.v)}async Ad(c){"macos-wkwebview"===
this.v&&this.dg();if("playable-ad"===this.v){this.ia=self.c3_base64files;this.Vb={};await this.af();for(let l=0,p=c.Qa.length;l<p;++l){var k=c.Qa[l].toLowerCase();this.Vb.hasOwnProperty(k)?c.Qa[l]={Mg:!0,Qg:this.Vb[k]}:this.ia.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ia[k]))}}c.Hg?this.F=c.Hg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Ug&&(this.ub=c.Ug);k=new MessageChannel;this.qa=k.port1;this.qa.onmessage=
l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Hf(l));this.hb=new self.Je(this);await P(this.hb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.pf(c,k.port2):await this.nf(c,k.port2)}Bc(c){c=this.ub.hasOwnProperty(c)?this.ub[c]:c.endsWith("/workermain.js")&&this.ub.hasOwnProperty("workermain.js")?this.ub["workermain.js"]:
"playable-ad"===this.v&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async lc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.v&&this.fb)return c=await this.vb(l.Lg?c:this.ec+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),
l)}return new Worker(c,l)}oa(){return Math.max(window.innerWidth,1)}fa(){return Math.max(window.innerHeight,1)}zd(c){var k=this.hb;return{baseUrl:this.F,windowInnerWidth:this.oa(),windowInnerHeight:this.fa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Ta(),projectData:c.$g,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Yg||"",exportType:c.he,isDebug:-1<
self.location.search.indexOf("debug"),ife:!!self.Zg,jobScheduler:{inputPort:k.Vc,outputPort:k.ad,maxNumWorkers:k.Dg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ec+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ec+"opus.wasm.wasm",isFileProtocol:this.fb,isiOSCordova:this.Ie(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async pf(c,k){var l=this.Bc(c.Tg);this.tb=await this.lc(l,this.F,{type:"module",name:"Runtime",
Lg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let p=c.gd||[],u=c.Qa;p=await Promise.all(p.map(r=>this.Da(r)));u=await Promise.all(u.map(r=>this.Da(r)));if("cordova"===this.v)for(let r=0,t=c.ic.length;r<t;++r){const y=c.ic[r],G=y[0];if(G===c.ed||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))y[1]=await this.Da(G)}this.tb.postMessage(Object.assign(this.zd(c),{type:"init-runtime",
isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.ic,mainProjectScript:c.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...Q(this.hb)]);this.Pb=E.map(r=>new r(this));this.yd();self.c3_callFunction=(r,t)=>this.Na.qf(r,t);"preview"===this.v&&(self.goToLastErrorScript=()=>this.sc("runtime","go-to-last-error-script"))}async nf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=
this.K;this.Pb=E.map(r=>new r(this));this.yd();var l=c.Qa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.gd)&&l.unshift(...c.gd);l=await Promise.all(l.map(r=>this.Da(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.ed,u=c.ic;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Da(t),await d(t),"preview"!==this.v||l[r]||this.Id(r,"main script did not run to completion")}catch(y){this.Id(r,y)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=
await this.Da(t),await d(t);"preview"===this.v&&"object"!==typeof self.Vg.Xg?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.zd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:K}),this.Cd(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Id(c,
k){this.Jb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Cd(){this.Jb()}Jb(){const c=window.Ig;c&&(c.parentElement.removeChild(c),window.Ig=null)}async wf(){const c=await R(this.hb);return{outputPort:c,transferables:[c]}}lf(){if(this.ca)throw Error("not available in worker mode");return this.Ia}sc(c,k,l,p,u){this.qa.postMessage({type:"event",
component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}rd(c,k,l,p,u){const r=I++,t=new Promise((y,G)=>{F.set(r,{resolve:y,reject:G})});this.qa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Bf(c);if("result"===k)this.Of(c);else if("runtime-ready"===k)this.Pf();else if("alert-error"===k)this.Jb(),alert(c.message);else if("creating-runtime"===k)this.Cd();else throw Error(`unknown message '${k}'`);
}Bf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Ib(u,!1,""+t);return}if(null===u)return r;r&&r.then?r.then(t=>this.Ib(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Ib(u,!1,""+t)}):this.Ib(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ib(c,
k,l){let p;l&&l.transferables&&(p=l.transferables);this.qa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Of(c){const k=c.responseId,l=c.isOk;c=c.result;const p=F.get(k);l?p.resolve(c):p.reject(c);F.delete(k)}C(c,k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static jc(c){if(E.includes(c))throw Error("DOM handler already added");E.push(c)}yd(){for(const c of this.Pb)if("runtime"===c.Za){this.Na=c;return}throw Error("cannot find runtime DOM handler");
}Hf(c){this.sc("debugger","message",c)}Pf(){for(const c of this.Pb)c.hd()}static Ta(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||h)}static Jd(c){h=!!c}We(c){this.La.push(c);this.Mc()}ag(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.yc()}Mc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Gg))}yc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Lf(){this.Ma=
-1;for(const c of this.La)c();this.Mc()}va(c){this.Na.va(c)}Ba(c){this.Na.Ba(c)}Lc(){this.Na.Lc()}Db(c){this.Na.Db(c)}He(){return!!B["audio/webm; codecs=opus"]}async zg(c){c=await this.rd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Fe(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}qd(c){return!this.Fe(c)}async Da(c){return"cordova"===this.v&&(c.startsWith("file:")||this.fb&&this.qd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),
c=await this.vb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async vf(c){const k=c.filename;switch(c.as){case "text":return await this.ye(k);case "buffer":return await this.vb(k);default:throw Error("unsupported type");}}ld(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async ye(c){c=await this.ld(c);return await D(c)}zc(){if(x.length&&!(8<=C)){C++;var c=x.shift();
this.bf(c.filename,c.Rg,c.Kg)}}vb(c){return new Promise((k,l)=>{x.push({filename:c,Rg:p=>{C--;this.zc();k(p)},Kg:p=>{C--;this.zc();l(p)}});this.zc()})}async bf(c,k,l){try{const p=await this.ld(c),u=await w(p);k(u)}catch(p){l(p)}}dg(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async af(){const c=
[];for(const [k,l]of Object.entries(this.ia))c.push(this.$e(k,l));await Promise.all(c)}async $e(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Vb[c]=k.str;else{let l=await this.jf(k);l||(l=this.df(k));this.ia[c]=l}}async jf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}df(c){c=this.Vf(c);return this.Ze(c.data,c.Ng)}Vf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Ng:c,data:l}}Ze(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,y;for(y=t=0;t<p;++t)r[t]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(l&=
3;l--;)u[y]=c.charCodeAt(y),++y;return new Blob([u],{type:k})}}}"use strict";
{const g=self.Bb;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function w(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function x(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function A(e){E.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function F(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await w(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.jc(class extends self.wb{constructor(e){super(e,"runtime");this.Td=!0;this.Oa=-1;this.cd="any";this.Kd=this.Ld=!1;this.Ha=
this.pb=this.xa=null;this.ac=this.$b=0;this.Xd=e.oa();this.Tb=e.fa();this.rb=0;e.C("canvas","update-size",c=>this.Sf(c));e.C("runtime","invoke-download",c=>this.Ff(c));e.C("runtime","raster-svg-image",c=>this.Mf(c));e.C("runtime","get-svg-image-size",c=>this.Df(c));e.C("runtime","set-target-orientation",c=>this.Qf(c));e.C("runtime","register-sw",()=>this.Nf());e.C("runtime","post-to-debugger",c=>this.Ed(c));e.C("runtime","go-to-script",c=>this.Ed(c));e.C("runtime","before-start-ticking",()=>this.uf());
e.C("runtime","debug-highlight",c=>this.xf(c));e.C("runtime","enable-device-orientation",()=>this.Ye());e.C("runtime","enable-device-motion",()=>this.Xe());e.C("runtime","add-stylesheet",c=>this.sf(c));e.C("runtime","alert",c=>this.tf(c));e.C("runtime","hide-cordova-splash",()=>this.Ef());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||x(k)||c.preventDefault()});const m=e.K;window.addEventListener("selectstart",
A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.mb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,
{passive:!1});window.addEventListener("resize",()=>this.Tf());window.addEventListener("fullscreenchange",()=>this.Va());window.addEventListener("webkitfullscreenchange",()=>this.Va());window.addEventListener("mozfullscreenchange",()=>this.Va());window.addEventListener("fullscreenerror",c=>this.Hc(c));window.addEventListener("webkitfullscreenerror",c=>this.Hc(c));window.addEventListener("mozfullscreenerror",c=>this.Hc(c));e.rc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;
if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):x(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Uf(c);this.Ja=new Set;this.Wb=new WeakSet;this.pa=!1}uf(){"cordova"===this.u.v?(document.addEventListener("pause",()=>this.Kc(!0)),document.addEventListener("resume",()=>this.Kc(!1))):document.addEventListener("visibilitychange",()=>this.Kc(document.hidden));
return{isSuspended:!(!document.hidden&&!I)}}hd(){window.addEventListener("focus",()=>this.Xa("window-focus"));window.addEventListener("blur",()=>{this.Xa("window-blur",{parentHasFocus:K()});this.mb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||x(h))&&this.Xa("keyboard-blur")});window.addEventListener("keydown",h=>this.Dd("keydown",h));window.addEventListener("keyup",h=>this.Dd("keyup",h));window.addEventListener("dblclick",h=>this.Ic("dblclick",h,d));window.addEventListener("wheel",
h=>this.Jf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.Cc(h);this.Wa("pointerdown",h)}),this.u.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.pb=new self.Ne(()=>this.gf(),5),this.pb.Od=!0,window.addEventListener("pointerrawupdate",h=>this.Kf(h))):window.addEventListener("pointermove",h=>this.Wa("pointermove",h)),window.addEventListener("pointerup",h=>this.Wa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Wa("pointercancel",
h))):(window.addEventListener("mousedown",h=>{this.Cc(h);this.Jc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Jc("pointermove",h)),window.addEventListener("mouseup",h=>this.Jc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Cc(h);this.Hb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Hb("pointermove",h)),window.addEventListener("touchend",h=>this.Hb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Hb("pointercancel",h)));const e=()=>this.Lc();
window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.u.Ge()&&!this.u.pd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Fc(this.fa(),navigator.virtualKeyboard.boundingRect.height)}))}Fc(e,h){document.body.style.transform="";if(0<h){var m=document.activeElement;
m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-h)/2,e>h&&(e=h),0>e&&(e=0),0<e&&(document.body.style.transform=`translateY(${-e}px)`))}}Xa(e,h){z(this,e,h||null,n)}oa(){return this.u.oa()}fa(){return this.u.fa()}Tf(){const e=this.oa(),h=this.fa();if(this.u.pd()){if(this.Xd===e&&h<this.Tb){this.rb=this.Tb-h;this.Fc(this.Tb,this.rb);return}0<this.rb&&(this.rb=0,this.Fc(h,this.rb));this.Xd=e;this.Tb=h}this.Xa("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,
isFullscreen:g.Ta()});this.u.rc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Fd(e,h,0))}bg(e,h,m){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Fd(e,h,m),48)}Fd(e,h,m){const c=this.oa(),k=this.fa();this.Oa=-1;c!=e||k!=h?this.Xa("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ta()}):10>m&&this.bg(c,k,m+1)}Qf(e){this.cd=e.targetOrientation}vg(){const e=this.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>
console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Va(){const e=g.Ta();e&&"any"!==this.cd&&this.vg();z(this,"fullscreenchange",
{isFullscreen:e,innerWidth:this.oa(),innerHeight:this.fa()})}Hc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);z(this,"fullscreenerror",{isFullscreen:g.Ta(),innerWidth:this.oa(),innerHeight:this.fa()})}Kc(e){e?this.u.yc():this.u.Mc();z(this,"visibilitychange",{hidden:e})}Dd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;H(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},
d)}Jf(e){z(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Ic(e,h,m){a(h)||H(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},m)}Jc(e,h){if(!a(h)){var m=this.mb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");
H(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.mb=h.buttons;this.Ic(h.type,h,f)}}Wa(e,h){if(this.pb&&"pointermove"!==e){var m=this.pb;m.eb||(N(m),m.Sb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.mb);H(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,
button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||0)+this.$b,movementY:(h.movementY||0)+this.ac,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);this.ac=this.$b=0;"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Ic(m,h,f),this.mb=
h.buttons)}Kf(e){this.Ha&&(this.$b+=this.Ha.movementX||0,this.ac+=this.Ha.movementY||0);this.Ha=e;e=this.pb;if(-1===e.Pa){var h=Date.now(),m=h-e.Sb,c=e.Bg;m>=c&&e.Od?(e.Sb=h,e.eb=!0,e.Pc(),e.eb=!1):e.Pa=self.setTimeout(e.ge,Math.max(c-m,4))}}gf(){this.Wa("pointermove",this.Ha);this.Ha=null}Hb(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];H(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,
pageY:k.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Cc(e){window!==window.top&&window.focus();this.Bd(e.target)&&document.activeElement&&!this.Bd(document.activeElement)&&document.activeElement.blur()}Bd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ye(){this.Ld||
(this.Ld=!0,window.addEventListener("deviceorientation",e=>this.zf(e)),window.addEventListener("deviceorientationabsolute",e=>this.Af(e)))}Xe(){this.Kd||(this.Kd=!0,window.addEventListener("devicemotion",e=>this.yf(e)))}zf(e){z(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Af(e){z(this,"deviceorientationabsolute",{absolute:!!e.absolute,
alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}yf(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});z(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},d)}Sf(e){const h=this.u.K;h.style.width=e.styleWidth+"px";
h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Td&&(h.style.display="",this.Td=!1)}Ff(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async Mf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);
return{imageBitmap:h,transferables:[h]}}async Df(e){return await self.C3_GetSvgImageSize(e.blob)}async sf(e){await q(e.url)}Lc(){var e=[...this.Ja];this.Ja.clear();if(!this.pa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Wb.has(h)||this.Ja.add(h)})}va(e){if("function"!==typeof e.play)throw Error("missing play function");this.Wb.delete(e);let h;try{h=e.play()}catch(m){this.Ja.add(e);return}h&&h.catch(()=>{this.Wb.has(e)||this.Ja.add(e)})}Ba(e){this.Ja.delete(e);this.Wb.add(e)}Db(e){this.pa=!!e}Ef(){navigator.splashscreen&&
navigator.splashscreen.hide&&navigator.splashscreen.hide()}xf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),this.xa.id="inspectOutline",document.body.appendChild(this.xa));var h=this.xa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Nf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ed(e){window.c3_postToMessagePort&&(e.from="runtime",
window.c3_postToMessagePort(e))}qf(e,h){return this.u.rd(this.Za,"js-invoke-function",{name:e,params:h},void 0,void 0)}tf(e){alert(e.message)}Uf(e){"entered-fullscreen"===e?(g.Jd(!0),this.Va()):"exited-fullscreen"===e?(g.Jd(!1),this.Va()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function P(g){if(g.Ag)throw Error("already initialised");g.Ag=!0;var a=g.dc.Bc("dispatchworker.js");g.Rc=await g.dc.lc(a,g.F,{name:"DispatchWorker"});a=new MessageChannel;g.Vc=a.port1;g.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.ad=await R(g)}function Q(g){return[g.Vc,g.ad]}
async function R(g){const a=g.Ud.length;var b=g.dc.Bc("jobworker.js");b=await g.dc.lc(b,g.F,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;g.Rc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);g.Ud.push(b);return f.port1}
self.Je=class{constructor(g){this.dc=g;this.F=g.F;this.F="preview"===g.v?this.F+"workers/":this.F+g.ec;this.Dg=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Ud=[];this.ad=this.Vc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Bb({Sg:!1,Tg:"workermain.js",Qa:["scripts/c3runtime.js"],ic:[],ed:"",Pg:"scripts/",gd:[],he:"html5"}));"use strict";
async function S(g,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());z(g,"permission-result",{type:a,result:b})}async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.Bb.jc(class extends self.wb{constructor(g){super(g,"touch");J(this,"request-permission",a=>S(this,a))}});"use strict";
{const g=180/Math.PI;self.da=class extends self.wb{constructor(a){super(a,"audio");this.Ob=this.c=null;this.Qb=this.Uc=!1;this.sa=()=>this.wg();this.$=[];this.D=[];this.ha=null;this.Vd="";this.Wd=-1;this.ob=new Map;this.Yc=1;this.pa=!1;this.dd=0;this.fc=1;this.Sc=0;this.Zd="HRTF";this.Pd="inverse";this.$d=600;this.Yd=1E4;this.be=1;this.Rd=this.bd=!1;this.ee=this.u.He();this.aa=new Map;this.Fa=new Set;this.Wc=!1;this.Zc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.If(b,d);this.Nb=null;
self.C3Audio_GetOutputStream=()=>this.Cf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.cf(b)],["play",b=>this.Wf(b)],["stop",b=>this.tg(b)],["stop-all",()=>this.ug()],["set-paused",b=>this.mg(b)],["set-volume",b=>this.rg(b)],["fade-volume",b=>this.hf(b)],["set-master-volume",b=>this.kg(b)],["set-muted",b=>this.lg(b)],["set-silent",b=>this.og(b)],["set-looping",b=>this.jg(b)],["set-playback-rate",b=>this.ng(b)],["seek",b=>this.cg(b)],["preload",b=>this.Xf(b)],["unload",b=>
this.xg(b)],["unload-all",()=>this.yg()],["set-suspended",b=>this.pg(b)],["get-suspended",()=>this.mf()],["add-effect",b=>this.wd(b)],["set-effect-param",b=>this.gg(b)],["remove-effects",b=>this.Zf(b)],["tick",b=>this.Rf(b)],["load-state",b=>this.Gf(b)]])}async cf(a){a.isiOSCordova&&(this.bd=!0);this.dd=a.timeScaleMode;this.Zd=["equalpower","HRTF","soundfield"][a.panningModel];this.Pd=["linear","inverse","exponential"][a.distanceModel];this.$d=a.refDistance;this.Yd=a.maxDistance;this.be=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.ee||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.xd();this.c.onstatechange=()=>{"running"!==this.c.state&&this.xd()};this.Ob=this.c.createGain();this.Ob.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.mc();try{await Promise.all(a.preloadList.map(d=>this.Fb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.c.sampleRate}}xd(){this.Qb||(this.Uc=!1,window.addEventListener("pointerup",this.sa,!0),window.addEventListener("touchend",this.sa,!0),window.addEventListener("click",this.sa,!0),window.addEventListener("keydown",this.sa,!0),this.Qb=!0)}ef(){this.Qb&&(this.Uc=!0,window.removeEventListener("pointerup",this.sa,!0),
window.removeEventListener("touchend",this.sa,!0),window.removeEventListener("click",this.sa,!0),window.removeEventListener("keydown",this.sa,!0),this.Qb=!1)}wg(){if(!this.Uc){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.ef()}}W(){return this.c}mc(){return this.c.currentTime}ta(){return this.Ob}nd(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.ta()}ie(a,
b){a=a.toLowerCase();let d=this.aa.get(a);d||(d=[],this.aa.set(a,d));b.ig(d.length);b.qg(a);d.push(b);this.Hd(a)}Hd(a){let b=this.ta();const d=this.aa.get(a);if(d&&d.length){b=d[0].P();for(let f=0,n=d.length;f<n;++f){const q=d[f];f+1===n?q.S(this.ta()):q.S(d[f+1].P())}}for(const f of this.ma(a))f.Oe(b);this.ya&&this.Zc===a&&(this.ya.disconnect(),this.ya.connect(b))}yb(){return this.Yc}zb(){return this.pa}hg(){this.Rd=!0}Ae(a,b){return b?this.u.zg(a).then(d=>{const f=this.c.createBuffer(1,d.length,
48E3);f.getChannelData(0).set(d);return f}):new Promise((d,f)=>{this.c.decodeAudioData(a,d,f)})}va(a){this.u.va(a)}Ba(a){this.u.Ba(a)}sd(a){let b=0;for(let d=0,f=this.D.length;d<f;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.f():++b}this.D.length=b}Pe(){let a=0;for(let b=0,d=this.$.length;b<d;++b){const f=this.$[b];this.$[a]=f;f.ua()?f.f():++a}this.$.length=a}*ma(a){if(a)for(const b of this.D)self.da.Be(b.Y,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Fb(a,b,d,f,n){for(const q of this.$)if(q.Sa()===
b)return await V(q),q;if(n)return null;f&&(this.bd||this.Rd)&&this.Pe();n="audio/webm; codecs=opus"===d&&!this.ee;f&&n&&this.hg();a=!f||this.bd||n?new self.we(this,a,b,d,f,n):new self.ue(this,a,b,d,f);this.$.push(a);await V(a);return a}async Ac(a,b,d,f,n){for(const q of this.D)if(q.Sa()===b&&(q.kc()||n))return q.Re(f),q;a=await this.Fb(a,b,d,n);f="html5"===a.Nc?new self.ve(a.i,a,f):new self.xe(a.i,a,f);this.D.push(f);return f}Ve(a){let b=this.ob.get(a);if(!b){let d=null;b={fd:0,Og:new Promise(f=>
d=f),resolve:d};this.ob.set(a,b)}b.fd++}$f(a){const b=this.ob.get(a);if(!b)throw Error("expected pending tag");b.fd--;0===b.fd&&(b.resolve(),this.ob.delete(a))}xc(a){a||(a=this.Vd);return(a=this.ob.get(a))?a.Og:Promise.resolve()}Gb(){if(0<this.Fa.size)M(this);else for(const a of this.D)if(a.od()){M(this);break}}Ca(){for(var a of this.Fa)a.Ca();a=this.mc();for(var b of this.D)b.Ca(a);b=this.D.filter(d=>d.od()).map(d=>d.Ra());z(this,"state",{tickCount:this.Wd,audioInstances:b,analysers:[...this.Fa].map(d=>
d.De())});0===b.length&&0===this.Fa.size&&this.Rb&&(this.u.ag(this.fe),this.Rb=!1)}tc(a,b,d){z(this,"trigger",{type:a,tag:b,aiid:d})}async Wf(a){const b=a.originalUrl,d=a.url,f=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,D=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.c.currentTime);this.Vd=q;this.Ve(q);try{this.ha=await this.Ac(b,d,f,q,n),w?(this.ha.Cb(!0),this.ha.Qe(w.x,
w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ha.Se(w.uid)):this.ha.Cb(!1),this.ha.Play(v,B,D,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.$f(q)}M(this)}tg(a){a=a.tag;for(const b of this.ma(a))b.na()}ug(){for(const a of this.D)a.na()}mg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Ua():d.Ab();this.Gb()}rg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Eb(a)}async hf(a){const b=a.tag,d=a.vol,
f=a.duration;a=a.stopOnEnd;await this.xc(b);for(const n of this.ma(b))n.Ce(d,f,a);this.Gb()}kg(a){this.Yc=a.vol;for(const b of this.D)b.Lb()}lg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.td(a)}og(a){this.pa=a.isSilent;this.u.Db(this.pa);for(const b of this.D)b.Kb()}jg(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.vc(a)}async ng(a){const b=a.tag;a=a.rate;await this.xc(b);for(const d of this.ma(b))d.vd(a)}async cg(a){const b=a.tag;a=a.pos;await this.xc(b);for(const d of this.ma(b))d.uc(a)}async Xf(a){const b=
a.originalUrl,d=a.url,f=a.type;a=a.isMusic;try{await this.Ac(b,d,f,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async xg(a){if(a=await this.Fb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}yg(){for(const a of this.$)a.f();this.$.length=0}pg(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.D)b.wc(a);a&&this.c.suspend&&this.c.suspend()}mf(){return this.c?this.c.state:"suspended"}Rf(a){this.fc=a.timeScale;this.Sc=
a.gameTime;this.Wd=a.tickCount;if(0!==this.dd)for(var b of this.D)b.Ea();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.D)f.ga===a&&f.ud(d.x,d.y,d.angle)}}async wd(a){var b=a.type;const d=a.tag;var f=a.params;if("filter"===b)f=new self.oe(this,...f);else if("delay"===b)f=new self.me(this,...f);else if("convolution"===b){b=null;try{b=await this.Fb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}f=new self.le(this,b.Z,...f);f.eg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.pe(this,...f);else if("phaser"===b)f=new self.re(this,...f);else if("gain"===b)f=new self.qe(this,...f);else if("tremolo"===b)f=new self.te(this,...f);else if("ringmod"===b)f=new self.se(this,...f);else if("distortion"===b)f=new self.ne(this,...f);else if("compressor"===b)f=new self.ke(this,...f);else if("analyser"===b)f=new self.je(this,...f);else throw Error("invalid effect type");this.ie(d,
f);this.Gd()}gg(a){const b=a.index,d=a.param,f=a.value,n=a.ramp,q=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,n,q),this.Gd())}Zf(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const d of b)d.f();this.aa.delete(a);this.Hd(a)}}Ue(a){this.Fa.add(a);this.Gb()}Yf(a){this.Fa.delete(a)}Gd(){this.Wc||(this.Wc=!0,Promise.resolve().then(()=>this.ff()))}ff(){const a={};for(const [b,d]of this.aa)a[b]=d.map(f=>f.Ra());z(this,"fxstate",{fxstate:a});this.Wc=!1}async Gf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.ua()&&1===b||(d.ua()||2!==b)&&d.na();for(const f of this.aa.values())for(const n of f)n.f();this.aa.clear();this.fc=a.timeScale;this.Sc=a.gameTime;d=a.listenerPos;this.c.listener.setPosition(d[0],d[1],d[2]);this.pa=a.isSilent;this.u.Db(this.pa);this.Yc=a.masterVolume;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(n=>this.wd(n))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.rf(f,b)));this.Gb()}async rf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,f=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,w=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Ac(d,f,n,v,q)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Me(a.pan);b.Play(B,D,w,0);a.isPlaying||b.Ua();b.Ec(a)}}}If(a,b){this.ya&&this.ya.disconnect();this.Zc=b.toLowerCase();this.ya=this.c.createMediaStreamSource(a);this.ya.connect(this.nd(this.Zc))}Cf(){this.Nb||(this.Nb=this.c.createMediaStreamDestination(),
this.Ob.connect(this.Nb));return this.Nb.stream}static Be(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Te(a){return a*g}static ze(a){return Math.pow(10,a/20)}static md(a){return Math.max(Math.min(self.da.ze(a),1),0)}static Le(a){return Math.log(a)/Math.log(10)*20}static Ke(a){return self.da.Le(Math.max(Math.min(a,1),0))}static Jg(a,b){return 1-Math.exp(-b*a)}};self.Bb.jc(self.da)}"use strict";function V(g){g.Ub||(g.Ub=g.Dc());return g.Ub}
self.jd=class{constructor(g,a,b,d,f){this.i=g;this.Fg=a;this.za=b;this.R=d;this.Cg=f;this.Nc="";this.Ub=null}f(){this.Ub=this.i=null}Dc(){}W(){return this.i.W()}oc(){return this.Fg}Sa(){return this.za}nc(){return this.R}ua(){return this.Cg}ea(){}};"use strict";
self.ue=class extends self.jd{constructor(g,a,b,d,f){super(g,a,b,d,f);this.Nc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.ib=this.jb=null;this.J.addEventListener("canplaythrough",()=>!0);this.nb=this.W().createGain();this.lb=null;this.J.addEventListener("canplay",()=>{this.jb&&(this.jb(),this.ib=this.jb=null);!this.lb&&this.J&&(this.lb=this.W().createMediaElementSource(this.J),this.lb.connect(this.nb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.za}' error: `,n);this.ib&&(this.ib(n),this.ib=this.jb=null)})}f(){this.i.sd(this);this.nb.disconnect();this.nb=null;this.lb.disconnect();this.lb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.f()}Dc(){return new Promise((g,a)=>{this.jb=g;this.ib=a;this.J.src=this.za})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function W(g){if(g.wa)return g.wa;var a=g.i.u;if("cordova"===a.v&&a.qd(g.za)&&a.fb)g.wa=await a.vb(g.za);else{a=await fetch(g.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.wa=await a.arrayBuffer()}}async function X(g){if(g.Z)return g.Z;g.Z=await g.i.Ae(g.wa,g.Eg);g.wa=null}
self.we=class extends self.jd{constructor(g,a,b,d,f,n){super(g,a,b,d,f);this.Nc="webaudio";this.Z=this.wa=null;this.Eg=!!n}f(){this.i.sd(this);this.Z=this.wa=null;super.f()}async Dc(){try{await W(this),await X(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.za}': `,g)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let g=0;self.kd=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Mb=g++;this.M=this.W().createGain();this.M.connect(this.ta());this.B=null;this.gb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.sb=1;this.Ga=!1;this.ra=1;a=this.i.dd;this.Xc=1===a&&!this.ua()||2===a;this.bb=this.ga=-1;this.de=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ta(){return this.i.nd(this.Y)}yb(){return this.i.yb()}xb(){return this.Xc?
this.i.Sc:performance.now()/1E3}oc(){return this.L.oc()}Sa(){return this.L.Sa()}nc(){return this.L.nc()}ua(){return this.L.ua()}Re(a){this.Y=a}T(){}kc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}od(){return!this.H&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}na(){}Ua(){}Ab(){}Eb(a){this.sb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.pc()}Ce(a,b,d){if(!this.Ga){a*=this.yb();var f=this.M.gain;f.cancelScheduledValues(0);var n=this.i.mc();b=n+b;f.setValueAtTime(f.value,
n);f.linearRampToValueAtTime(a,b);this.sb=a;this.bb=b;this.de=d}}Lb(){this.Eb(this.sb)}Ca(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.de&&this.na(),this.i.tc("fade-ended",this.Y,this.Mb))}pc(){const a=this.sb*this.yb();return isFinite(a)?a:0}td(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Kb())}zb(){return this.i.zb()}Kb(){}vc(){}vd(a){this.ra!==a&&(this.ra=a,this.Ea())}Ea(){}uc(){}wc(){}Cb(a){a=!!a;this.gb!==a&&((this.gb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Zd,this.B.distanceModel=
this.i.Pd,this.B.refDistance=this.i.$d,this.B.maxDistance=this.i.Yd,this.B.rolloffFactor=this.i.be),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ta())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ta())))}Qe(a,b,d,f,n,q){this.gb&&(this.ud(a,b,d),a=self.da.Te,this.B.coneInnerAngle=a(f),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}ud(a,b,d){this.gb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Se(a){this.ga=a}qc(){}Oe(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Mb,tag:this.Y,duration:this.ea(),volume:this.sb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.ra,uid:this.ga,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.ua(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.qc(),pan:this.Ee()}}Ec(a){this.vd(a.playbackRate);this.td(a.isMuted)}Ee(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Me(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Cb(!1)}}}"use strict";
self.ve=class extends self.kd{constructor(g,a,b){super(g,a,b);this.L.nb.connect(this.M);this.L.onended=()=>this.Gc()}f(){this.na();this.L.nb.disconnect();super.f()}O(){return this.L.O()}Gc(){this.H=!0;this.ga=-1;this.i.tc("ended",this.Y,this.Mb)}T(){return this.O().ended}kc(){return this.H?!0:this.T()}Aa(){let g=this.O().currentTime;this.V||(g=Math.min(g,this.ea()));return g}Play(g,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.Eb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,f)}this.i.va(d);this.G=this.H=!1;this.V=g;this.ra=1}na(){const g=this.O();g.paused||g.pause();this.i.Ba(g);this.H=!0;this.G=!1;this.ga=-1}Ua(){if(!(this.G||this.H||this.T())){var g=this.O();g.paused||g.pause();this.i.Ba(g);this.G=!0}}Ab(){!this.G||this.H||this.T()||(this.i.va(this.O()),this.G=!1)}Kb(){this.O().muted=this.Ga||this.zb()}vc(g){g=!!g;this.V!==g&&
(this.V=g,this.O().loop=g)}Ea(){let g=this.ra;this.Xc&&(g*=this.i.fc);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}uc(g){if(!this.H&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}qc(){return this.Aa()}wc(g){g?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.va(this.O()),this.la=!1)}};"use strict";
function Y(g){g.j&&g.j.disconnect();g.j=null;g.Ya=null}
self.xe=class extends self.kd{constructor(g,a,b){super(g,a,b);this.j=null;this.Xb=d=>this.Gc(d);this.Tc=!0;this.Ya=null;this.N=this.Yb=this.Zb=0;this.$c=1}f(){this.na();Y(this);this.Xb=null;super.f()}Gc(g){this.G||this.la||g.target!==this.Ya||(this.H=this.Tc=!0,this.ga=-1,Y(this),this.i.tc("ended",this.Y,this.Mb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Tc}kc(){return!this.j||this.H?!0:this.T()}Aa(){let g;g=this.G?this.N:this.Yb+(this.xb()-this.Zb)*this.ra;this.V||(g=Math.min(g,this.ea()));
return g}Play(g,a,b,d){this.$c=1;this.Eb(a);Y(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Xb;this.j.loop=g;this.j.start(d,b);this.G=this.H=this.Tc=!1;this.V=g;this.ra=1;this.Zb=this.xb();this.Yb=b}na(){if(this.j)try{this.j.stop(0)}catch(g){}this.H=!0;this.G=!1;this.ga=-1}Ua(){this.G||this.H||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Ab(){!this.G||this.H||this.T()||(Y(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Ea(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.G=!1)}pc(){return super.pc()*this.$c}Kb(){this.$c=this.Ga||this.zb()?0:1;this.Lb()}vc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Ea(){let g=this.ra;this.Xc&&(g*=this.i.fc);this.j&&(this.j.playbackRate.value=g)}uc(g){this.H||this.T()||(this.G?this.N=g:(this.Ua(),this.N=g,this.Ab()))}qc(){return this.N}wc(g){g?
this.IsPlaying()?(this.la=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(Y(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Ea(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.la=!1)}Ec(g){super.Ec(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.c=a.W();this.Sd=-1;this.R=this.Y="";this.g=null}f(){this.c=null}ig(a){this.Sd=a}qg(a){this.Y=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var n=this.c.currentTime;f+=n;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,f)}}}Ra(){return{type:this.R,tag:this.Y,params:this.g}}}
self.oe=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.R="filter";this.g=[b,d,f,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.A=this.c.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=f;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}f(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,f)}}};self.me=class extends g{constructor(a,b,d,f){super(a);this.R="delay";this.g=[b,d,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.kb=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=d;this.l.connect(this.kb);this.l.connect(this.a);this.kb.connect(this.b);this.kb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.kb)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.kb.disconnect();this.U.disconnect();this.ab.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){const n=self.da.md;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 4:this.g[1]=n(b);this.m(this.ab.gain,n(b),d,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,f)}}};self.le=class extends g{constructor(a,b,d,f){super(a);this.R="convolution";this.g=[d,f];this.Nd=this.Md="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.$a=this.c.createConvolver();this.$a.normalize=d;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}f(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}eg(a,b){this.Md=a;this.Nd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Md;a.bufferUrl="";a.bufferType=this.Nd;return a}};self.pe=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="flanger";this.g=[b,d,f,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.cb=this.o();this.cb.gain.value=n;this.U=this.c.createDelay(b+d);this.U.delayTime.value=b;this.s=this.c.createOscillator();this.s.frequency.value=f;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}f(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,d,f)}}};self.re=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.R="phaser";this.g=[b,d,f,n,q,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.A=this.c.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=f;this.s=this.c.createOscillator();this.s.frequency.value=q;this.I=this.o();this.I.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.s.connect(this.I);this.I.connect(this.A.frequency);this.s.start(0)}f(){this.s.stop(0);this.l.disconnect();this.A.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,f)}}};self.qe=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){const n=self.da.md;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,f)}}};self.te=class extends g{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.c.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}f(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,f);this.m(this.I.gain,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.se=class extends g{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.qb=this.o();this.qb.gain.value=
0;this.s=this.c.createOscillator();this.s.frequency.value=b;this.s.connect(this.qb.gain);this.s.start(0);this.l.connect(this.qb);this.l.connect(this.a);this.qb.connect(this.b)}f(){this.s.stop(0);this.s.disconnect();this.qb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,f);
this.m(this.a.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.ne=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="distortion";this.g=[b,d,f,n,q];this.l=this.o();this.cc=this.o();this.bc=this.o();this.fg(f,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.hc=this.c.createWaveShaper();this.Qc=new Float32Array(65536);this.kf(b,d);this.hc.curve=this.Qc;this.l.connect(this.cc);this.l.connect(this.a);this.cc.connect(this.hc);this.hc.connect(this.bc);
this.bc.connect(this.b)}f(){this.l.disconnect();this.cc.disconnect();this.hc.disconnect();this.bc.disconnect();this.b.disconnect();this.a.disconnect();super.f()}fg(a,b){.01>a&&(a=.01);this.cc.gain.value=a;this.bc.gain.value=Math.pow(1/a,.6)*b}kf(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.sg(f,a,b);this.Qc[32768+d]=f;this.Qc[32768-d-1]=-f}}sg(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.da.Jg(f-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}};self.ke=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="compressor";this.g=[b,d,f,n,q];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.je=class extends g{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Qd=new Float32Array(this.h.frequencyBinCount);this.ce=new Uint8Array(b);this.ae=this.Ka=0;this.i.Ue(this)}f(){this.i.Yf(this);this.h.disconnect();super.f()}Ca(){this.h.getFloatFrequencyData(this.Qd);this.h.getByteTimeDomainData(this.ce);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let f=(this.ce[d]-128)/128;0>f&&(f=-f);
this.Ka<f&&(this.Ka=f);b+=f*f}d=self.da.Ke;this.Ka=d(this.Ka);this.ae=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}De(){return{tag:this.Y,index:this.Sd,peak:this.Ka,rms:this.ae,binCount:this.h.frequencyBinCount,freqBins:this.Qd}}}};
